### ISSUE TITLE
Upload to F-Droid app store

### ISSUE THREAD

**Issue by betsythefc** [rootkiwi/an2linuxclient#1]
Hello, I found this app via reddit, and I wanted to see if the app could be added to the F-Droid app repo so people without Google play can get it.

https://f-droid.org/wiki/page/Inclusion_Policy
https://f-droid.org/forums/forum/submission-queue/

**Comment by jessebolson** [comment]
+1

**Comment by est31** [comment]
Uploaded: https://gitlab.com/fdroid/fdroiddata/commit/4358b27147ca83672404b80b333112bfff4ab176

**Comment by BenjaminHCCarr** [comment]
Thanks @est31

**Comment by Tonus1** [comment]
Shouldn't that be closed?

**Comment by rootkiwi** [comment]
yes
