### ISSUE TITLE
Suggestion: a little widget

### ISSUE THREAD

**Issue by Macchiarch** [rootkiwi/an2linuxclient#11]
It would be great if there was a widget to enable and disable the application.
Something like a toggle button.

**Comment by rootkiwi** [comment]
Yes that could be useful

**Comment by flocke** [comment]
Additionally a quick settings tile with the same function would be nice.

**Comment by rootkiwi** [comment]
yeah, will start working on an2linux and fix a few things when I have time. kinda busy in school at the moment and also learning golang :)

**Comment by rootkiwi** [comment]
I added a quick settings tile, skipped the widget for now, I felt the tile was enough as it works like a toggle button.

Though quick settings tile is only supported from Android 7.0+ (SDK 24).
