### ISSUE TITLE
Connection Timed Out when Pairing 

### ISSUE THREAD

**Issue by bicodegas** [rootkiwi/an2linuxclient#17]
Hi,
I've been using AN2Linux (using the Wifi option) for some time now, it always worked flawlessly. I noted 2 days ago I wasn't getting the notifications from my phone. After several attempts tinkering the configuration I choose to reinstall the app, delete the config file on my linux machine and start over.

The server part works, it starts and keeps waiting for connections. The problem seems to be that client cannot pair with the server, I always get the "connection timed out warning".

The only thing that I installed on my phone that could mess with AN2Linux is a firewall (AFWall+) but I'm sure I set it right so AN2Linux could run without any problem. I disabled the firewall to see if it was blocking anything but I got the connection timed out error anyway.

Any idea what could be blocking the pairing?

Thanks in advance,
Cheers

**Comment by rootkiwi** [comment]
Hmm that is strange, I wonder what the problem was.

Well great that it is working now. Yes can be closed for now, reopen if you have problems again.

**Comment by bicodegas** [comment]
hi, @rootkiwi 

First, thank you for you app. Simple, does what it says and no hassle.

I'm guessing that it was the firewall, maybe it wasn't really turned off for AN2Linux even though I tried to remove the rules and disabled it. It's working now, if something changes I'll let you know. Thank you.
Cheers.

**Comment by rootkiwi** [comment]
I'm glad you like it :)

Yea hopefully that's it, yes good you do that. Cheers
