### ISSUE TITLE
Add support for emojis

### ISSUE THREAD

**Issue by ple103** [rootkiwi/an2linuxclient#2]

**Comment by rootkiwi** [comment]
If the notifications use Unicode emojis which the apps I've tried do it should work. I've only tried with the notification daemon that I use (dunst) so I'm not sure if it works on others aswell.
http://www.unicode.org/emoji/charts/full-emoji-list.html

Try this python3 program:
```
#!/usr/bin/env python3
from gi.repository import Notify
Notify.init('test')
Notify.Notification.new('Emojis', '😀😁😂😃😄😅😆😉😊', '').show()
```
