### ISSUE TITLE
Suggestion: Make app available for Android 4.3 (SDK v18)

### ISSUE THREAD

**Issue by blitzter47** [rootkiwi/an2linuxclient#26]
I would like to try this app, but it is only available for Android 4.4+. I wish to use it on my phone on Android 4.3.

**Comment by rootkiwi** [comment]
Will look into that

**Comment by rootkiwi** [comment]
minSdkVersion will be changed from 19 to 18 in next version. 

NotificationListenerService (https://developer.android.com/reference/android/service/notification/NotificationListenerService) was introduced in sdk 18, so I can not go below that. Though it might still be possible to read notifications before that as well using some other method, I don't know.

For now minSdkVersion will be 18 (Android 4.3) but title and message extraction from notification will not be supported.

Becase simple extraction of data from notification was introduced in sdk 19. https://developer.android.com/reference/android/app/Notification.html#extras

Again, extraction of notification title/message might still be possible below sdk 19 using reflection or something. But for now Android 4.3 users will not get notification title/message data.
