### ISSUE TITLE
Google inbox notification not sync to pc.

### ISSUE THREAD

**Issue by mac1202** [rootkiwi/an2linuxclient#5]
Hi I use an2linux since several days everything is working fine except for inbox notification, they aren't displayed on my pc.

**Comment by rootkiwi** [comment]
You mean the app `Inbox by Gmail` and not the normal `Gmail` app?

A few things I could think about at the moment even though I've not tried Inbox by Gmail app is:

- Set config setting on computer `list_size_duplicates = 0`
- Make sure you have the latest version 0.2.0 and disable all blocking settings in the app
- Make sure the app is enabled in Enabled applications in the app

If it still don't work I would have to try it myself.

**Comment by mac1202** [comment]
Yes i mean the Inbox by gmail app.
Client version is 0.2.0 and app is enabled in client config.
I will try the list_size_duplicates = 0 in serveur config, and disabled all blocking setting in the client.

**Comment by mac1202** [comment]
Unchecking block group summary notification fixed it. Thank you.

**Comment by rootkiwi** [comment]
Great
