### ISSUE TITLE
Future direction of app

### ISSUE THREAD

**Issue by matteofilia** [rootkiwi/an2linuxclient#7]
Hello,

I am wondering what the future direction of this app is, if any.

I was wondering if there are plans to allow more integration between Linux and your phone (such as checking battery level or setting your phone to silent), or if this project is intended to be for notifications only.

**Comment by rootkiwi** [comment]
Hey!

No there are not any plans for that, I like it to just focus on notifications. Maybe add some features around that like logging etc.
