### ISSUE TITLE
Phone notifications with a changing status cause a new notification on the desktop every few seconds

### ISSUE THREAD

**Issue by Jereviendrai** [rootkiwi/an2linuxclient#8]
The offending notification is F-Droid's "Updating Repositories" info. It contains a short status line that says something like "300mb out of 600mb done". It is updated every second or so, and every time it is updated, a new notification shows up on my desktop, which is rather annoying.

It would be nice if an2linux could prevent this sort of spamming. If possible, it would be nice if the existing Desktop notification would be updated similarly to the Android notification. Otherwise it might be possible to limit the amount of notifications per app per time interval, or detect whether it's the same notification and don't send it again.

**Comment by rootkiwi** [comment]
At the moment the possibilities for you is to remove F-Droid from enabled applications in an2linux settings.

There is a setting on the server side to not show duplicates but that uses a hash to compare so if anything is changed in the notification then it does not count as a duplicate.

Thanks for your suggestions!

**Comment by esp13** [comment]
I don't know if it is the same (my english is very bad) but for exemple when K9-mail is checking for new mails it create unwanted new notifications like "cheching mails in xxx@xxx:INBOX"
I suppose one of the further options can permit too keep only permanent notification: 

- "Block ongoing event notifications" 
- "Block running service notifications"
- "Block group summary notifications"
- "Block local notifications"

=> I think we have to check "block ongoing event notification", I am right?

**Comment by rootkiwi** [comment]
> => I think we have to check "block ongoing event notification", I am right?

Yes you are correct. That should work, depending on how the app creates the notification.

**int FLAG_ONGOING_EVENT:**
> Bit to be bitwise-ored into the flags field that should be set if this notification is in reference to something that is ongoing, like a phone call. It should not be set if this notification is in reference to something that happened at a particular point in time, like a missed phone call.

**Comment by esp13** [comment]
Nice :)

Is it possible or will be possible to check this options per apps? Checked for K9-Mail, unchecked for incoming call for example?

**Comment by rootkiwi** [comment]
I like the idea but I can not promise when it will be implemented :)

**Comment by esp13** [comment]
Nice :)
The I suggest the fourth filter option can become lists of apps you can individually check, non or all.
I don't really know how github works,is there an other section better where to put suggestions?

**Comment by rootkiwi** [comment]
Yes thank you, `issues` is fine for suggestions for me :)
