### ISSUE TITLE
SVG icons

### ISSUE THREAD

**Issue by conrad-heimbold** [rootkiwi/an2linuxclient#9]
Hi, I restyled the icons for an2linux as svg's, you could use them...
- natively in Android since API level 21 (Android 5)
- for the server part on the desktop ( linux desktop env's support svg)
- to generate pngs easily in all kinds of sizes with inkscape: 
```
SIZES="32 48 64 72 96 128 144 192 256 384 512" 
for SIZE in $SIZES
do
inkscape --export-png="${FILENAME}-${SIZE}x${SIZE}.png" --export-width=${SIZE} --export-height=${SIZE} ${FILENAME}.svg
done
```

Please go to my gist: https://gist.github.com/conrad-heimbold/fa5193ca1587025d1500cafae99cbbd6 
(Github does not allow direct uploading of svg). 

If the icons should be changed, please tell me. 

Credits: 
The Tux mascot included has been styled by "Milan Kohut" ( https://www.iconfinder.com/milan.kohut ), who would like to be mentioned.

**Comment by rootkiwi** [comment]
Cool, will play around with that a little with color #1DE9B6. Thanks!

**Comment by conrad-heimbold** [comment]
Any update on this? 

I added one more icon (the last one), that one should look much better.

**Comment by rootkiwi** [comment]
Wow, really love that new one! Just tried it, it will be the new icon (in color) for/from next release. I liked the other ones too but this new one is just awesome. And looks great in color too!

Thank you!

**Comment by conrad-heimbold** [comment]
an improved version of the svg an2linux icon can also be found in the forked ICEcons app at https://github.com/dkanada/ICEcons/ ( or /conrad_heimbold/ICEcons ) in the folder icons/an2linux.svg
